### ISSUE TITLE
Sharings

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/vaccination-metadata#11]
Initial thoughts:

- [x] categoryOptions.publicAccess = "rwrw"
- [x] [app] teams -> publicAccess: "rwrw----" (required by sync)
- [x] Sharings for dashboard: See last comment.
 http://dev2.eyeseetea.com:8082/api/metadata.json?users:filter=dataViewOrganisationUnits.id:eq:[vB9T3dc2fqY,vB9T3dc2fqY]&users:fields=id,name,dataViewOrganisationUnits

**Comment by adrianq** [comment]
Evaluate and estimate the 2 approaches for sharings for dashboards:
- Approach 1
   - Add the group "Vaccination Referents"
      - Edit for all the users
   - Add all users that have their "Data output and analytics org units" at level L4 selected for any of the campaign/dataset orgunits"
      - Edit for users with role: Medical Focal Point
      - View for the rest
   - Add all users that have their "Data output and analytics org units" at level L3 selected for any of the campaign/dataset orgunits"
      - Edit for users with role: Medco
      - View for the rest
   - Extract all organisation unit of L3 linked to the campaign. Look if this organisation unit is part of the organisation unit group belonging to organisation unit group set "8. Operational Cells  Group Set?". Add the user group that has the same name than the organisation unit group.
      - Edit for users with role: TesaCo
      - View for the rest
   - Add the group "HMIS Officers"

- Approach 2:
   - Allows the user choosing the user/s and/or usergroup/s and the mode (edit/read) for the dashboard campaign. New step?

**Comment by adrianq** [comment]
Final Decision:
   - [x] Add the group "Vaccination Referents" and "HMIS Officers" with edit permissions.
   - [x] Get all users that have their "Data output and analytics org units" at level L4 selected for any of the campaign/dataset orgunits" and set *edit* for those with role *Population data entry*
   - [x] Get all users that have their "Data output and analytics org units" at level L3 selected for any of the campaign/dataset orgunits", and set *edit* for those with role *Medco*
   - [x] Get all organisation unit of L3 linked to the campaign. Look if this organisation unit is part of the organisation unit group belonging to organisation unit group set "8. Operational Cells  Group Set?". Add the user group that has the same name than the organisation unit group -> and set *edit* for users in this group with role *TesaCo*.

(Note there aren't any *view* permissions)
